### ISSUE TITLE
Staging tags are created based on computer's date, not UTC

### ISSUE THREAD

**Issue by ericandrewlewis** [technicalpickles/capistrano-gitflow#12]
Staging tags are created with `Date.today`, which is the computer's date. 

This means someone in Singapore might deploy on July 20th at 2am (July 19 6pm UTC), creating a staging tag of `staging-2017-07-20-xxx`, and later (chronologically) someone in New York might deploy on July 19th at 6pm (July 19 10pm UTC), creating a staging tag of `staging-2017-07-19-xxx`. When deploying this will cause issues because Capistrano sees the earlier deploy from Singapore as the latest staging tag.

**Comment by bogdanRada** [comment]
Hello. Thanks for submitting this issue. I have seen the PR associated with this issue. I will merge it as soon as i have a bit of time.
Thank you for your contribution.

**Comment by bogdanRada** [comment]
merged the pull request and released version 1.6.0 on rubygems.org https://rubygems.org/gems/capistrano-gitflow/versions/1.6.0

Thank you very much for your contribution. Have a nice day :)
