### ISSUE TITLE
`last_production_tag` no method found error when deploying the same production tag

### ISSUE THREAD

**Issue by zocoi** [technicalpickles/capistrano-gitflow#7]
Here is the offending line: https://github.com/technicalpickles/capistrano-gitflow/blob/master/lib/capistrano/gitflow/helpers/helper.rb#L200

`last_production_tag` should be renamed to `gitflow_last_production_tag `

**Comment by bogdanRada** [comment]
closing as per pull request #8  which has been merged into master 322d0427b125e15f6716161e77dcbaeb7d4b7d5d
