### ISSUE TITLE
Clean up old and outdated tags

### ISSUE THREAD

**Issue by zocoi** [technicalpickles/capistrano-gitflow#9]
Hi

After a while, git repo are left with lots of deploy tags starts with `staging-<timestamp>-<txt>` and `production-<timestamp>-<txt>`. It would be great that we set an option similar to capistrano `keep_releases` to only keep a number of latest tags and clean up the rest.

Thanks

**Comment by bogdanRada** [comment]
As a simple contributor to this project  I like the idea but i am though a bit concerned about messing with git  history since this is a destructive action although this could be used only optionally.
    @technicalpickles, what do you think? Would a feature like this be of interest? If yes i could give it a try next week when i have some free time and implement this if you agree .

**Comment by technicalpickles** [comment]
It seems like a reasonable feature to me. If you've been using it for awhile and deploy a lot, you'd have a ton of tags. Depending on how you use tags, this could be considered 'clutter', but in general it shouldn't hurt anything.

Implementation wise, I'd imagine there being a new capistrano task to handle cleaning. After the new tag was created makes sense. You could also leave this up to a project's user to hook into the capistrano lifecycle. Might be worth looking at how `keep_releases` works, and mimic that behavior too.

**Comment by bogdanRada** [comment]
Didn't had yet time to work on this but will try next week to work on it. Sorry for keeping you waiting

**Comment by bogdanRada** [comment]
Had opened pull request #10 that should fix this issue.

**Comment by bogdanRada** [comment]
Pull request #10  was merged into master. I am closing this issue for now
